# Generated by Django 3.2.4 on 2021-06-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('subid', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, max_length=200)),
            ],
        ),
    ]
