# Generated by Django 3.2.4 on 2021-06-17 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_subject_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('quesid', models.IntegerField(primary_key=True, serialize=False)),
                ('desc', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('opid', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question')),
            ],
        ),
    ]
