# Generated by Django 3.2.4 on 2021-06-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_option_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='desc',
            field=models.TextField(max_length=500, null='true'),
            preserve_default='true',
        ),
    ]
