# Generated by Django 3.2.4 on 2021-06-17 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_option_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.subject'),
        ),
        migrations.AlterField(
            model_name='option',
            name='desc',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='opid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='quesid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
