# Generated by Django 3.2.4 on 2021-06-18 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20210617_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='desc',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='desc',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exam.subject'),
            preserve_default=False,
        ),
    ]
