# Generated by Django 3.2.4 on 2021-06-18 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20210618_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='desc',
            new_name='opttext',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='desc',
            new_name='questext',
        ),
    ]
