# Generated by Django 3.2.4 on 2021-06-22 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_auto_20210622_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='user',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
